apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wikiparser-remote-tmp-cache
  labels:
    app: wikiparser-remote
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikiparser-remote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikiparser-remote
  template:
    metadata:
      labels:
        app: wikiparser-remote
    spec:
      containers:
      - name: wikiparser-remote
        image: registry.datexis.com/toberhauser/bender-remote:0.3.0
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: wikiparser-pvc
          mountPath: /parser
        - name: ssh-key
          mountPath: /root/ssh-key
        - name: tmp-cache
          mountPath: /tmp
        ports:
          - containerPort: 22
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "cat /root/ssh-key/id_rsa.pub >> /root/.ssh/authorized_keys"]
        resources:
          requests:
            memory: 1k
            cpu: 2
      imagePullSecrets:
      - name: private-registry-auth
      volumes:
        - name: ssh-key
          secret:
            secretName: my-ssh-public-key
            defaultMode: 256
        - name: wikiparser-pvc
          persistentVolumeClaim:
            claimName: wikiparser-pvc
        - name: tmp-cache
          persistentVolumeClaim:
            claimName: wikiparser-remote-tmp-cache